/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CreateBillRouteImport } from './routes/create-bill'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartiesIdRouteImport } from './routes/parties.$id'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBillRoute = CreateBillRouteImport.update({
  id: '/create-bill',
  path: '/create-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRoute = PartiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/create-bill': typeof CreateBillRoute
  '/expenses': typeof ExpensesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/parties': typeof PartiesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/parties/$id': typeof PartiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/create-bill': typeof CreateBillRoute
  '/expenses': typeof ExpensesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/parties': typeof PartiesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/parties/$id': typeof PartiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/create-bill': typeof CreateBillRoute
  '/expenses': typeof ExpensesRoute
  '/export': typeof ExportRoute
  '/import': typeof ImportRoute
  '/inventory': typeof InventoryRoute
  '/parties': typeof PartiesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/parties/$id': typeof PartiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/auth'
    | '/connections'
    | '/create-bill'
    | '/expenses'
    | '/export'
    | '/import'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/parties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/auth'
    | '/connections'
    | '/create-bill'
    | '/expenses'
    | '/export'
    | '/import'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/parties/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/auth'
    | '/connections'
    | '/create-bill'
    | '/expenses'
    | '/export'
    | '/import'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/requests'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/parties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  ConnectionsRoute: typeof ConnectionsRoute
  CreateBillRoute: typeof CreateBillRoute
  ExpensesRoute: typeof ExpensesRoute
  ExportRoute: typeof ExportRoute
  ImportRoute: typeof ImportRoute
  InventoryRoute: typeof InventoryRoute
  PartiesRoute: typeof PartiesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-bill': {
      id: '/create-bill'
      path: '/create-bill'
      fullPath: '/create-bill'
      preLoaderRoute: typeof CreateBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteImport
      parentRoute: typeof PartiesRoute
    }
  }
}

interface PartiesRouteChildren {
  PartiesIdRoute: typeof PartiesIdRoute
}

const PartiesRouteChildren: PartiesRouteChildren = {
  PartiesIdRoute: PartiesIdRoute,
}

const PartiesRouteWithChildren =
  PartiesRoute._addFileChildren(PartiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  ConnectionsRoute: ConnectionsRoute,
  CreateBillRoute: CreateBillRoute,
  ExpensesRoute: ExpensesRoute,
  ExportRoute: ExportRoute,
  ImportRoute: ImportRoute,
  InventoryRoute: InventoryRoute,
  PartiesRoute: PartiesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
