/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseVoucherRouteImport } from './routes/purchase-voucher'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CreateBillRouteImport } from './routes/create-bill'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const PurchaseVoucherRoute = PurchaseVoucherRouteImport.update({
  id: '/purchase-voucher',
  path: '/purchase-voucher',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBillRoute = CreateBillRouteImport.update({
  id: '/create-bill',
  path: '/create-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/create-bill': typeof CreateBillRoute
  '/inventory': typeof InventoryRoute
  '/purchase-voucher': typeof PurchaseVoucherRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/create-bill': typeof CreateBillRoute
  '/inventory': typeof InventoryRoute
  '/purchase-voucher': typeof PurchaseVoucherRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/create-bill': typeof CreateBillRoute
  '/inventory': typeof InventoryRoute
  '/purchase-voucher': typeof PurchaseVoucherRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/auth'
    | '/create-bill'
    | '/inventory'
    | '/purchase-voucher'
    | '/reports'
    | '/settings'
    | '/team'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/auth'
    | '/create-bill'
    | '/inventory'
    | '/purchase-voucher'
    | '/reports'
    | '/settings'
    | '/team'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/auth'
    | '/create-bill'
    | '/inventory'
    | '/purchase-voucher'
    | '/reports'
    | '/settings'
    | '/team'
    | '/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  CreateBillRoute: typeof CreateBillRoute
  InventoryRoute: typeof InventoryRoute
  PurchaseVoucherRoute: typeof PurchaseVoucherRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-voucher': {
      id: '/purchase-voucher'
      path: '/purchase-voucher'
      fullPath: '/purchase-voucher'
      preLoaderRoute: typeof PurchaseVoucherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-bill': {
      id: '/create-bill'
      path: '/create-bill'
      fullPath: '/create-bill'
      preLoaderRoute: typeof CreateBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  CreateBillRoute: CreateBillRoute,
  InventoryRoute: InventoryRoute,
  PurchaseVoucherRoute: PurchaseVoucherRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
